version: '3'
services:
  db:
    image: mysql:latest
    container_name: project_name_mariadb
    restart: "always"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  backend:
    build: 
      context: ./mysite/
      dockerfile: Dockerfile
    container_name: shopping_list
    working_dir: /shopping_list/mysite
    entrypoint: ./docker-entrypoint.sh
    restart: "no"
    volumes:
      - .:/shopping_list
    ports:
      - "8000:8000"
    environment:
      - TEST=${TEST:-}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  data:
