version: '3'
services:
  db:
    image: mysql:latest
    container_name: project_name_mariadb
    restart: "always"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  backend:
    build: 
      context: ./mysite/
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: shopping_list
    working_dir: /shopping_list/mysite
    entrypoint: ./docker-entrypoint.sh
    restart: "no"
    volumes:
      - ./mysite:/shopping_list/mysite
      - static_backend:/var/www/static/
      - venv_env:/venv_env
    #Only for development
    #ports:
    #  - "8000:8000"
    environment:
      - TEST=${TEST:-}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /shopping_list/frontend
    restart: "no"
    volumes:
      - ./frontend:/shopping_list/frontend
      - /shopping_list/frontend/node_modules
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  server:
    build:
      context: ./server/
    container_name: apache_server
    ports:
      - "80:80"
    volumes:
      - ./mysite:/app/mysite
      - static_backend:/var/www/static/backend
      - venv_env:/venv_env
    env_file:
      - .env
volumes:
  data:
  venv_env:
  static_backend:
