name: Test back- and frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build containers
      run: docker-compose -f "docker-compose.yaml" up --build -d

    - name: Flush database
      run: |
        docker-compose -f "docker-compose.yaml" exec backend bash -c "python manage.py flush --no-input"

    - name: Makemigrations
      run: |
        docker-compose -f "docker-compose.yaml" exec backend bash -c "python manage.py makemigrations"

    - name: Migrate
      run: |
        docker-compose -f "docker-compose.yaml" exec backend bash -c "python manage.py migrate --noinput"

    - name: Check Migration Status
      run: |
        docker-compose -f "docker-compose.yaml" exec backend bash -c "python manage.py showmigrations"

    - name: Run backend tests
      run: |
        docker-compose -f "docker-compose.yaml" exec backend bash -c "python manage.py test shopping_list"

    - name: Run frontend tests
      run: |
        docker-compose -f "docker-compose.yaml" exec frontend npm test